#!/usr/bin/env python3
"""Regenerate tailwind-fonts.css: @font-face rules with the woff2 files
base64-inlined as data URIs.

Why inline rather than url("fonts/…"): `dx` hashes and flattens declared assets
and does NOT copy files merely referenced from CSS, nor rewrite their url().
A relative reference therefore 404s in both `dx serve` and the embedded binary.
Inlining is the one form that behaves identically in dev and in the shipped
binary with no server route and no dx cooperation, and it removes the flash of
fallback text a runtime-injected @font-face would cause.

Run after changing anything in assets/fonts/, then rebuild:
    python3 gen-font-css.py && dx build --package raptor-ui
"""
import base64
import pathlib

FACES = [
    ("Barlow", 400, "barlow-400.woff2"),
    ("Barlow", 500, "barlow-500.woff2"),
    ("Barlow", 600, "barlow-600.woff2"),
    ("Barlow", 700, "barlow-700.woff2"),
    ("Barlow Condensed", 600, "barlow-condensed-600.woff2"),
    ("Barlow Condensed", 700, "barlow-condensed-700.woff2"),
    ("IBM Plex Mono", 400, "ibm-plex-mono-400.woff2"),
    ("IBM Plex Mono", 500, "ibm-plex-mono-500.woff2"),
]

here = pathlib.Path(__file__).parent
out = [
    "/* GENERATED by gen-font-css.py — do not edit by hand.",
    " * Latin-subset woff2, base64-inlined so the fonts survive dx's asset",
    " * hashing and the server's rust-embed bundle without a route or a CDN.",
    " */",
]
total = 0
for family, weight, filename in FACES:
    data = (here / "assets" / "fonts" / filename).read_bytes()
    total += len(data)
    b64 = base64.b64encode(data).decode("ascii")
    out.append(
        "@font-face{font-family:'%s';font-style:normal;font-weight:%d;"
        "font-display:swap;src:url(data:font/woff2;base64,%s) format('woff2')}"
        % (family, weight, b64)
    )
(here / "tailwind-fonts.css").write_text("\n".join(out) + "\n")
print(f"tailwind-fonts.css: {len(FACES)} faces, {total // 1024}KB of font data")
